"$schema" = 'https://starship.rs/config-schema.json'

format = "$time$status$all"
add_newline = false

# # Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# # Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[time]
disabled = false
format = '[$time]($style) '

[status]
disabled = false
format = '[$common_meaning$signal_name$symbol$status]($style) '
map_symbol = true

[git_branch]
symbol = " "

[git_metrics]
disabled = false

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[aws]
symbol = "  "

[buf]
disabled = true
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
disabled = true
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[java]
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Debian = " "
Fedora = " "
Linux = " "
Macos = " "
RedHatEnterprise = " "
Ubuntu = " "
Windows = "󰍲 "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
