;;; tkzw-theme.el --- created by takezawa

(deftheme tkzw
  "created by takezawa")

(custom-theme-set-faces 'tkzw
                        '(default ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "apple" :family "Ricty"))))
                        '(bold ((t (:background "grey40" :foreground "yellow" :weight bold))))
                        '(bold-italic ((t (:slant italic :weight bold))))
                        '(underline ((t (:underline t))))
                        '(fixed-pitch ((t (:family "Monospace"))))
                        '(variable-pitch ((t (:family "Sans Serif"))))
                        '(shadow ((t (:foreground "grey70"))))
                        '(link ((t (:foreground "cyan1" :underline t))))
                        '(link-visited ((t (:foreground "violet" :underline t))))
                        '(highlight ((t (:background "blue3"))))
                        '(region ((t (:background "skyblue" :foreground "black"))))
                        '(secondary-selection ((t (:background "darkslateblue" :foreground "black"))))
                        '(trailing-whitespace ((t (:background "red1"))))
                        '(escape-glyph ((t (:foreground "cyan"))))
                        '(nobreak-space ((t (:foreground "cyan" :underline t))))
                        '(mode-line ((t (:background "DarkRed" :foreground "white" :box (:line-width 1 :style released-button)))))
                        '(mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
                        '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
                        '(mode-line-emphasis ((t (:weight bold))))
                        '(mode-line-buffer-id ((t (:background "DarkRed" :foreground "white" :weight bold))))
                        '(header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
                        '(minibuffer-prompt ((t (:foreground "cyan"))))
                        '(fringe ((t (:background "grey10"))))
                        '(border ((t (:background "black"))))
                        '(cursor ((t (:background "yellow"))))
                        '(mouse ((t (:background "sienna1"))))
                        '(completions-first-difference ((t (:background "grey40" :foreground "yellow" :weight bold))))
                        '(completions-common-part ((t (:stipple nil :background "black" :foreground "White" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "bitstream" :family "M+2VM+IPAG circle"))))
                        '(button ((t (:underline t))))
                        '(next-error ((t (:background "skyblue" :foreground "black"))))
                        '(font-lock-comment-face ((t (:foreground "OrangeRed"))))
                        '(font-lock-comment-delimiter-face ((t (:foreground "OrangeRed"))))
                        '(font-lock-string-face ((t (:foreground "LightSalmon"))))
                        '(font-lock-doc-face ((t (:foreground "LightSalmon"))))
                        '(font-lock-keyword-face ((t (:foreground "Cyan"))))
                        '(font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
                        '(font-lock-function-name-face ((t (:foreground "LightSkyBlue"))))
                        '(font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
                        '(font-lock-type-face ((t (:foreground "PaleGreen"))))
                        '(font-lock-constant-face ((t (:foreground "Aquamarine"))))
                        '(font-lock-warning-face ((t (:foreground "Pink" :weight bold))))
                        '(font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
                        '(font-lock-regexp-grouping-backslash ((t (:background "grey40" :foreground "yellow" :weight bold))))
                        '(font-lock-regexp-grouping-construct ((t (:background "grey40" :foreground "yellow" :weight bold))))
                        '(isearch ((t (:background "blue" :foreground "brown4"))))
                        '(isearch-fail ((t (:background "red4"))))
                        '(lazy-highlight ((t (:background "paleturquoise4"))))
                        '(file-name-shadow ((t (:foreground "grey70"))))
                        '(query-replace ((t (:background "blue"))))
                        '(match ((t (:background "RoyalBlue3"))))
                        '(buffer-menu-buffer ((t (:weight bold))))
                        '(ns-working-text-face ((t (:underline "gray80"))))
                        '(ns-marked-text-face ((t (:underline "gray80"))))
                        '(ns-unmarked-text-face ((t (:underline "gray20"))))
                        '(tooltip ((t (:background "lightyellow" :foreground "black" :family "Sans Serif"))))
                        '(flymake-errline ((t (:background "red4" :weight bold))))
                        '(flymake-warnline ((t (:background "yellow4" :weight bold))))
                        '(comint-highlight-input ((t (:weight bold))))
                        '(comint-highlight-prompt ((t (:foreground "cyan1"))))
                        '(compilation-error ((t (:foreground "Pink" :weight bold))))
                        '(compilation-warning ((t (:foreground "Orange" :weight bold))))
                        '(compilation-info ((t (:foreground "Green1" :weight bold))))
                        '(compilation-line-number ((t (:foreground "LightGoldenrod"))))
                        '(compilation-column-number ((t (:foreground "PaleGreen"))))
                        '(show-paren-match ((t (:background "steelblue3"))))
                        '(show-paren-mismatch ((t (:background "purple" :foreground "white"))))
                        '(grep-edit-face ((t (:background "SlateGray1" :foreground "Black" :weight bold))))
                        '(grep-edit-file-face ((t (:background "gray30" :weight bold))))
                        '(grep-edit-reject-face ((t (:foreground "hot pink" :weight bold))))
                        '(grep-edit-done-face ((t (:foreground "LightSkyBlue" :weight bold))))
                        '(widget-documentation ((t (:foreground "lime green"))))
                        '(widget-button ((t (:weight bold))))
                        '(widget-field ((t (:background "dim gray"))))
                        '(widget-single-line-field ((t (:background "dim gray"))))
                        '(widget-inactive ((t (:foreground "light gray"))))
                        '(widget-button-pressed ((t (:foreground "red"))))
                        '(dired-header ((t (:foreground "PaleGreen"))))
                        '(dired-mark ((t (:foreground "Aquamarine"))))
                        '(dired-marked ((t (:foreground "Pink" :weight bold))))
                        '(dired-flagged ((t (:foreground "Pink" :weight bold))))
                        '(dired-warning ((t (:foreground "Pink" :weight bold))))
                        '(dired-perm-write ((t (:foreground "OrangeRed"))))
                        '(dired-directory ((t (:foreground "LightSkyBlue"))))
                        '(dired-symlink ((t (:foreground "Cyan"))))
                        '(dired-ignored ((t (:foreground "grey70"))))
                        '(ffap ((t (:background "blue3"))))
                        '(anything-header ((t (:background "grey20" :foreground "grey90" :box (:line-width 1 :style released-button)))))
                        '(anything-isearch-match ((t (:background "Yellow"))))
                        '(anything-visible-mark ((t (:background "green1" :foreground "black"))))
                        '(anything-buffer-saved-out ((t (:foreground "red"))))
                        '(anything-buffer-not-saved ((t (:foreground "Indianred2"))))
                        '(anything-ff-prefix ((t (:background "yellow" :foreground "black"))))
                        '(anything-ff-executable ((t (:foreground "green"))))
                        '(anything-ff-directory ((t (:background "LightGray" :foreground "DarkRed"))))
                        '(anything-ff-symlink ((t (:foreground "DarkOrange"))))
                        '(anything-ff-invalid-symlink ((t (:background "red" :foreground "black"))))
                        '(anything-ff-file ((t (:foreground "CadetBlue" :underline t))))
                        '(anything-grep-file ((t (:foreground "BlueViolet" :underline t))))
                        '(anything-grep-lineno ((t (:foreground "Darkorange1"))))
                        '(anything-grep-running ((t (:foreground "Red"))))
                        '(anything-grep-finish ((t (:foreground "Green"))))
                        '(anything-M-x-key-face ((t (:foreground "orange" :underline t))))
                        '(anything-bmkext-info ((t (:foreground "green"))))
                        '(anything-bmkext-w3m ((t (:foreground "yellow"))))
                        '(anything-bmkext-gnus ((t (:foreground "magenta"))))
                        '(anything-bmkext-man ((t (:foreground "Orange4"))))
                        '(anything-bmkext-no--file ((t (:foreground "grey"))))
                        '(anything-bmkext-file ((t (:foreground "Deepskyblue2"))))
                        '(anything-bookmarks-su-face ((t (:foreground "red"))))
                        '(anything-w3m-bookmarks-face ((t (:foreground "cyan1" :underline t))))
                        '(anything-emms-playlist ((t (:foreground "Springgreen4" :underline t))))
                        '(anything-apt-installed ((t (:foreground "green"))))
                        '(anything-gentoo-match-face ((t (:foreground "red"))))
                        '(anything-overlay-line-face ((t (:background "IndianRed4" :underline t))))
                        '(anything-match ((t (:background "RoyalBlue3"))))
                        '(moccur-face ((t (:background "light grey" :foreground "Black" :weight bold))))
                        '(moccur-current-line-face ((t (:underline t))))
                        '(search-buffers-face ((t (:background "SkyBlue" :foreground "Black" :weight bold))))
                        '(search-buffers-header-face ((t (:background "gray20" :foreground "azure3" :weight bold))))
                        '(eldoc-highlight-function-argument ((t (:background "grey40" :foreground "yellow" :weight bold))))
                        '(yas/field-highlight-face ((t (:background "DimGrey"))))
                        '(dropdown-list-face ((t (:stipple nil :background "lightyellow" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "bitstream" :family "M+2VM+IPAG circle"))))
                        '(dropdown-list-selection-face ((t (:stipple nil :background "purple" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "bitstream" :family "M+2VM+IPAG circle"))))
                        '(my-face-r-1 ((t (:background "gray5"))))
                        '(my-face-b-1 ((t (:background "gray"))))
                        '(my-face-b-2 ((t (:background "gray26"))))
                        '(my-face-u-1 ((t (:foreground "SteelBlue" :underline t))))
                        '(dircolors-face-dir ((t (:foreground "SkyBlue"))))
                        '(dircolors-face-doc ((t (:foreground "MediumTurquoise"))))
                        '(dircolors-face-html ((t (:foreground "Plum"))))
                        '(dircolors-face-package ((t (:foreground "IndianRed"))))
                        '(dircolors-face-tar ((t (:foreground "OrangeRed"))))
                        '(dircolors-face-dos ((t (:foreground "LimeGreen"))))
                        '(dircolors-face-sound ((t (:foreground "LightBlue"))))
                        '(dircolors-face-img ((t (:foreground "Salmon"))))
                        '(dircolors-face-ps ((t (:foreground "BlueViolet"))))
                        '(dircolors-face-backup ((t (:foreground "Magenta"))))
                        '(dircolors-face-make ((t (:foreground "Khaki"))))
                        '(dircolors-face-paddb ((t (:foreground "Orange"))))
                        '(dircolors-face-lang ((t (:foreground "Yellow"))))
                        '(dircolors-face-emacs ((t (:foreground "GreenYellow"))))
                        '(dircolors-face-lang-interface ((t (:foreground "Goldenrod"))))
                        '(dircolors-face-yacc ((t (:foreground "Coral"))))
                        '(dircolors-face-objet ((t (:foreground "DimGray"))))
                        '(dircolors-face-asm ((t (:foreground "Tan"))))
                        '(dircolors-face-compress ((t (:foreground "Sienna"))))
                        '(cua-rectangle ((t (:background "maroon" :foreground "white"))))
                        '(cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
                        '(cua-global-mark ((t (:background "yellow1" :foreground "black"))))
                        '(highlight-changes ((t (:background "midnight blue" :foreground "red1"))))
                        '(highlight-changes-delete ((t (:background "gray30" :foreground "red1" :underline t))))
                        '(elscreen-tab-background-face ((t (:background "Gray50"))))
                        '(elscreen-tab-control-face ((t (:background "white" :foreground "black" :underline "Gray50"))))
                        '(elscreen-tab-current-screen-face ((t (:background "white" :foreground "black"))))
                        '(elscreen-tab-other-screen-face ((t (:background "Gray85" :foreground "Gray50" :underline t))))
                        '(cperl-nonoverridable-face ((t (:foreground "SkyBlue"))))
                        '(cperl-array-face ((t (:background "navy" :foreground "darkseagreen" :weight bold))))
                        '(cperl-hash-face ((t (:background "navy" :foreground "darkseagreen" :slant italic :weight bold))))
                        '(hbfc-face ((t (:background "red" :foreground "red" :inverse-video t))))
                        '(change-log-date ((t (:foreground "LightSalmon"))))
                        '(change-log-name ((t (:foreground "Aquamarine"))))
                        '(change-log-email ((t (:foreground "LightGoldenrod"))))
                        '(change-log-file ((t (:foreground "LightSkyBlue"))))
                        '(change-log-list ((t (:foreground "Cyan"))))
                        '(change-log-conditionals ((t (:foreground "LightGoldenrod"))))
                        '(change-log-function ((t (:foreground "LightGoldenrod"))))
                        '(change-log-acknowledgement ((t (:foreground "OrangeRed"))))
                        '(diff-header ((t (:background "grey45"))))
                        '(diff-file-header ((t (:background "grey60" :weight bold))))
                        '(diff-index ((t (:background "grey60" :weight bold))))
                        '(diff-hunk-header ((t (:background "grey45"))))
                        '(diff-function ((t (:background "grey45"))))
                        '(diff-context ((t (:foreground "grey70"))))
                        '(diff-nonexistent ((t (:background "grey60" :weight bold))))
                        '(diff-refine-change ((t (:background "grey60"))))
                        '(magit-section-title ((t (:foreground "OrangeRed" :weight bold))))
                        '(magit-branch ((t (:weight bold))))
                        '(magit-diff-hunk-header ((t (:foreground "cyan3" :slant italic))))
                        '(magit-diff-add ((t (:foreground "green"))))
                        '(magit-diff-none ((t (:foreground "gray70"))))
                        '(magit-diff-del ((t (:foreground "OrangeRed"))))
                        '(magit-log-graph ((t (:foreground "grey30"))))
                        '(magit-log-sha1 ((t (:foreground "tomato"))))
                        '(magit-item-highlight ((t (:background "gray15"))))
                        '(magit-item-mark ((t (:foreground "orange"))))
                        '(magit-log-tag-label ((t (:background "DarkGoldenRod"))))
                        '(magit-log-head-label-bisect-good ((t (:background "light green" :foreground "dark olive green" :box 1))))
                        '(magit-log-head-label-bisect-bad ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
                        '(magit-log-head-label-remote ((t (:background "Grey11" :foreground "DarkSeaGreen2" :box 1))))
                        '(magit-log-head-label-tags ((t (:background "LemonChiffon1" :foreground "goldenrod4" :box 1))))
                        '(magit-log-head-label-patches ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
                        '(magit-log-head-label-local ((t (:background "Grey13" :foreground "LightSkyBlue1" :box 1))))
                        '(magit-menu-selected-option ((t (:foreground "orange"))))
                        '(popup-face ((t (:background "lightgray" :foreground "black"))))
                        '(popup-scroll-bar-foreground-face ((t (:background "black"))))
                        '(popup-scroll-bar-background-face ((t (:background "gray"))))
                        '(popup-isearch-match ((t (:background "sky blue"))))
                        '(popup-tip-face ((t (:background "khaki1" :foreground "black"))))
                        '(popup-menu-face ((t (:background "lightgray" :foreground "black"))))
                        '(popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
                        '(ac-completion-face ((t (:foreground "darkgray" :underline t))))
                        '(ac-candidate-face ((t (:background "lightgray" :foreground "black" :underline "darkgray"))))
                        '(ac-selection-face ((t (:background "steelblue" :foreground "white"))))
                        '(ac-gtags-candidate-face ((t (:background "lightgray" :foreground "navy"))))
                        '(ac-gtags-selection-face ((t (:background "navy" :foreground "white"))))
                        '(ac-yasnippet-candidate-face ((t (:background "sandybrown" :foreground "black"))))
                        '(ac-yasnippet-selection-face ((t (:background "coral3" :foreground "white"))))
                        '(company-tooltip ((t (:background "yellow" :foreground "black"))))
                        '(company-tooltip-selection ((t (:background "orange1" :foreground "black"))))
                        '(company-tooltip-mouse ((t (:background "blue3"))))
                        '(company-tooltip-common ((t (:background "yellow" :foreground "red"))))
                        '(company-tooltip-common-selection ((t (:background "orange1" :foreground "red"))))
                        '(company-preview ((t (:background "blue4" :foreground "wheat"))))
                        '(company-preview-common ((t (:background "blue4" :foreground "red"))))
                        '(company-preview-search ((t (:background "blue1" :foreground "wheat"))))
                        '(company-echo-common ((t (:foreground "firebrick1"))))
                        '(zmacs-region ((t (:background "snow" :foreground "blue"))))
                        '(yellow ((t (:foreground "yellow"))))
                        '(xref-list-symbol-face ((t (:foreground "navy"))))
                        '(xref-list-pilot-face ((t (:foreground "navy"))))
                        '(xref-keyword-face ((t (:foreground "blue"))))
                        '(woman-unknown-face ((t (:foreground "LightSalmon"))))
                        '(woman-italic-face ((t (:foreground "beige"))))
                        '(woman-bold-face ((t (:weight bold))))
                        '(text-cursor ((t (:background "yellow" :foreground "black"))))
                        '(red ((t (:foreground "red"))))
                        '(qt-classes-face ((t (:foreground "Red"))))
                        '(primary-selection ((t (:background "blue"))))
                        '(p4-diff-ins-face ((t (:foreground "blue"))))
                        '(p4-diff-head-face ((t (:background "gray95"))))
                        '(p4-diff-file-face ((t (:background "gray90"))))
                        '(p4-diff-del-face ((t (:foreground "red"))))
                        '(p4-diff-change-face ((t (:foreground "dark green"))))
                        '(p4-depot-unmapped-face ((t (:foreground "grey30"))))
                        '(p4-depot-deleted-face ((t (:foreground "red"))))
                        '(p4-depot-added-face ((t (:foreground "blue"))))
                        '(modeline-mousable-minor-mode ((t (:background "DarkRed" :foreground "white"))))
                        '(modeline-mousable ((t (:background "DarkRed" :foreground "white"))))
                        '(message-separator-face ((t (:foreground "blue3"))))
                        '(message-mml-face ((t (:foreground "ForestGreen"))))
                        '(message-header-xheader-face ((t (:foreground "blue"))))
                        '(message-header-to-face ((t (:foreground "green2" :weight bold))))
                        '(message-header-subject-face ((t (:foreground "green3"))))
                        '(message-header-other-face ((t (:foreground "#b00000"))))
                        '(message-header-newsgroups-face ((t (:foreground "yellow" :slant italic :weight bold))))
                        '(message-header-name-face ((t (:foreground "DarkGreen"))))
                        '(message-header-cc-face ((t (:foreground "green4" :weight bold))))
                        '(message-cited-text-face ((t (:foreground "red"))))
                        '(list-mode-item-selected ((t (:background "gray68" :foreground "white"))))
                        '(isearch-secondary ((t (:foreground "red3"))))
                        '(info-xref ((t (:foreground "DodgerBlue1" :underline t))))
                        '(info-node ((t (:foreground "DodgerBlue1" :underline t :weight bold))))
                        '(info-menu-5 ((t (:underline t))))
                        '(holiday-face ((t (:background "chocolate4"))))
                        '(highline-face ((t (:background "SeaGreen"))))
                        '(highlight-changes-7 ((t (:background "midnight blue" :foreground "DarkOrchid"))))
                        '(highlight-changes-6 ((t (:background "midnight blue" :foreground "green4"))))
                        '(highlight-changes-5 ((t (:background "midnight blue" :foreground "firebrick"))))
                        '(highlight-changes-4 ((t (:background "midnight blue" :foreground "maroon"))))
                        '(highlight-changes-3 ((t (:background "midnight blue" :foreground "blue"))))
                        '(highlight-changes-2 ((t (:background "midnight blue" :foreground "magenta"))))
                        '(highlight-changes-1 ((t (:background "midnight blue" :foreground "yellow"))))
                        '(gui-element ((t (:background "#D4D0C8" :foreground "black"))))
                        '(gui-button-face ((t (:background "grey75" :foreground "black"))))
                        '(green ((t (:foreground "green"))))
                        '(gnus-summary-selected-face ((t (:underline t))))
                        '(gnus-summary-normal-ticked-face ((t (:foreground "pink"))))
                        '(gnus-summary-normal-read-face ((t (:foreground "PaleGreen"))))
                        '(gnus-summary-normal-ancient-face ((t (:foreground "SkyBlue"))))
                        '(gnus-summary-low-ticked-face ((t (:foreground "pink" :slant italic))))
                        '(gnus-summary-low-read-face ((t (:foreground "PaleGreen" :slant italic))))
                        '(gnus-summary-low-ancient-face ((t (:foreground "SkyBlue" :slant italic))))
                        '(gnus-summary-high-unread-face ((t (:weight bold))))
                        '(gnus-summary-high-ticked-face ((t (:foreground "pink" :weight bold))))
                        '(gnus-summary-high-read-face ((t (:foreground "PaleGreen" :weight bold))))
                        '(gnus-summary-high-ancient-face ((t (:foreground "SkyBlue" :weight bold))))
                        '(gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
                        '(gnus-splash-face ((t (:foreground "Brown"))))
                        '(gnus-signature-face ((t (:foreground "khaki" :weight bold))))
                        '(gnus-header-subject-face ((t (:foreground "orange" :weight bold))))
                        '(gnus-header-newsgroups-face ((t (:foreground "purple" :weight bold))))
                        '(gnus-header-name-face ((t (:foreground "deep sky blue"))))
                        '(gnus-header-from-face ((t (:foreground "spring green" :weight bold))))
                        '(gnus-header-content-face ((t (:foreground "forest green"))))
                        '(gnus-group-news-low-face ((t (:foreground "DarkTurquoise" :weight bold))))
                        '(gnus-group-news-low-empty-face ((t (:foreground "DarkTurquoise"))))
                        '(gnus-group-news-6-face ((t (:weight bold))))
                        '(gnus-group-news-5-face ((t (:weight bold))))
                        '(gnus-group-news-4-face ((t (:weight bold))))
                        '(gnus-group-news-3-face ((t (:weight bold))))
                        '(gnus-group-news-2-face ((t (:foreground "turquoise" :weight bold))))
                        '(gnus-group-news-2-empty-face ((t (:foreground "turquoise"))))
                        '(gnus-group-news-1-face ((t (:foreground "PaleTurquoise" :weight bold))))
                        '(gnus-group-news-1-empty-face ((t (:foreground "PaleTurquoise"))))
                        '(gnus-group-mail-low-face ((t (:foreground "aquamarine4" :weight bold))))
                        '(gnus-group-mail-low-empty-face ((t (:foreground "aquamarine4"))))
                        '(gnus-group-mail-3-face ((t (:foreground "aquamarine3" :weight bold))))
                        '(gnus-group-mail-3-empty-face ((t (:foreground "aquamarine3"))))
                        '(gnus-group-mail-2-face ((t (:foreground "aquamarine2" :weight bold))))
                        '(gnus-group-mail-2-empty-face ((t (:foreground "aquamarine2"))))
                        '(gnus-group-mail-1-face ((t (:foreground "aquamarine1" :weight bold))))
                        '(gnus-group-mail-1-empty-face ((t (:foreground "aquamarine1"))))
                        '(gnus-emphasis-underline-italic ((t (:underline t))))
                        '(gnus-emphasis-underline-bold-italic ((t (:underline t :weight bold))))
                        '(gnus-emphasis-underline-bold ((t (:underline t :weight bold))))
                        '(gnus-emphasis-underline ((t (:underline t))))
                        '(gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
                        '(gnus-emphasis-bold-italic ((t (:weight bold))))
                        '(gnus-emphasis-bold ((t (:weight bold))))
                        '(gnus-cite-face-9 ((t (:foreground "violet"))))
                        '(gnus-cite-face-8 ((t (:foreground "magenta"))))
                        '(gnus-cite-face-7 ((t (:foreground "orange"))))
                        '(gnus-cite-face-6 ((t (:foreground "chocolate" :weight bold))))
                        '(gnus-cite-face-5 ((t (:foreground "pale green"))))
                        '(gnus-cite-face-4 ((t (:foreground "light pink"))))
                        '(gnus-cite-face-3 ((t (:foreground "gold" :weight bold))))
                        '(gnus-cite-face-2 ((t (:foreground "cadetblue" :weight bold))))
                        '(gnus-cite-face-11 ((t (:foreground "turquoise"))))
                        '(gnus-cite-face-10 ((t (:foreground "medium purple"))))
                        '(gnus-cite-face-1 ((t (:foreground "deep sky blue" :weight bold))))
                        '(font-lock-reference-face ((t (:foreground "SlateBlue"))))
                        '(font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
                        '(fl-type-face ((t (:foreground "cyan"))))
                        '(fl-string-face ((t (:foreground "light coral"))))
                        '(fl-keyword-face ((t (:foreground "LightGreen"))))
                        '(fl-function-name-face ((t (:foreground "green"))))
                        '(fl-doc-string-face ((t (:foreground "purple"))))
                        '(fl-comment-face ((t (:foreground "medium purple"))))
                        '(eshell-prompt-face ((t (:foreground "MediumAquamarine"))))
                        '(eshell-ls-unreadable-face ((t (:foreground "DimGray"))))
                        '(eshell-ls-symlink-face ((t (:foreground "White"))))
                        '(eshell-ls-special-face ((t (:foreground "Gold"))))
                        '(eshell-ls-readonly-face ((t (:foreground "Aquamarine"))))
                        '(eshell-ls-product-face ((t (:foreground "sandybrown"))))
                        '(eshell-ls-picture-face ((t (:foreground "Violet"))))
                        '(eshell-ls-missing-face ((t (:foreground "black"))))
                        '(eshell-ls-executable-face ((t (:foreground "Coral"))))
                        '(eshell-ls-directory-face ((t (:foreground "MediumSlateBlue" :weight bold))))
                        '(eshell-ls-clutter-face ((t (:foreground "DimGray"))))
                        '(eshell-ls-backup-face ((t (:foreground "Grey"))))
                        '(eshell-ls-archive-face ((t (:foreground "IndianRed" :weight bold))))
                        '(erc-underline-face ((t (:underline t))))
                        '(erc-prompt-face ((t (:foreground "MediumAquamarine"))))
                        '(erc-pal-face ((t (:foreground "pale green"))))
                        '(erc-notice-face ((t (:foreground "MediumAquamarine"))))
                        '(erc-inverse-face ((t (:background "wheat" :foreground "darkslategrey"))))
                        '(erc-input-face ((t (:foreground "Beige"))))
                        '(erc-error-face ((t (:foreground "IndianRed" :weight bold))))
                        '(erc-direct-msg-face ((t (:foreground "sandybrown"))))
                        '(erc-bold-face ((t (:weight bold))))
                        '(erc-action-face ((t (:weight bold))))
                        '(diary-face ((t (:foreground "yellow1"))))
                        '(custom-variable-tag-face ((t (:foreground "light blue" :underline t))))
                        '(custom-variable-button-face ((t (:underline t :weight bold))))
                        '(custom-state-face ((t (:foreground "lime green"))))
                        '(custom-set-face ((t (:background "white" :foreground "blue"))))
                        '(custom-saved-face ((t (:underline t))))
                        '(custom-rogue-face ((t (:background "black" :foreground "pink"))))
                        '(custom-modified-face ((t (:background "blue" :foreground "white"))))
                        '(custom-invalid-face ((t (:background "red" :foreground "yellow"))))
                        '(custom-group-tag-face-1 ((t (:foreground "pink" :underline t))))
                        '(custom-group-tag-face ((t (:foreground "light blue" :underline t))))
                        '(custom-face-tag-face ((t (:underline t))))
                        '(custom-changed-face ((t (:background "blue" :foreground "white"))))
                        '(calendar-today-face ((t (:underline t))))
                        '(buffers-tab ((t (:background "black" :foreground "white"))))
                        '(blue ((t (:foreground "blue"))))
                        '(anything-file-name ((t (:foreground "Blue"))))
                        '(anything-ffiles-prefix-face ((t (:background "yellow" :foreground "black"))))
                        '(anything-dired-symlink-face ((t (:foreground "DarkOrange"))))
                        '(anything-dir-priv ((t (:background "LightGray" :foreground "DarkRed"))))
                        '(anything-dir-heading ((t (:background "Pink" :foreground "Blue"))))
                        '(ipa ((t (:foreground "green"))))
                        '(calendar-today ((t (:underline t))))
                        '(diary ((t (:foreground "yellow1"))))
                        '(holiday ((t (:background "chocolate4"))))
                        '(org-hide ((t (:foreground "black"))))
                        '(org-drawer ((t (:foreground "LightSkyBlue"))))
                        '(org-column ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 140 :family "Ricty"))))
                        '(org-column-title ((t (:background "grey30" :underline t :weight bold))))
                        '(org-footnote ((t (:foreground "Cyan" :underline t))))
                        '(org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
                        '(org-target ((t (:underline t))))
                        '(org-date ((t (:foreground "Cyan" :underline t))))
                        '(org-sexp-date ((t (:foreground "Cyan"))))
                        '(org-tag ((t (:weight bold))))
                        '(org-todo ((t (:foreground "Pink" :weight bold))))
                        '(org-done ((t (:foreground "PaleGreen" :weight bold))))
                        '(org-agenda-done ((t (:foreground "PaleGreen"))))
                        '(org-headline-done ((t (:foreground "LightSalmon"))))
                        '(org-table ((t (:foreground "LightSkyBlue"))))
                        '(org-formula ((t (:foreground "chocolate1"))))
                        '(org-document-title ((t (:foreground "pale turquoise" :weight bold :height 1.44))))
                        '(org-document-info ((t (:foreground "pale turquoise"))))
                        '(org-clock-overlay ((t (:background "SkyBlue4"))))
                        '(org-agenda-structure ((t (:foreground "LightSkyBlue"))))
                        '(org-agenda-date-today ((t (:slant italic :weight bold))))
                        '(org-agenda-date-weekend ((t (:weight bold))))
                        '(org-scheduled ((t (:foreground "PaleGreen"))))
                        '(org-scheduled-today ((t (:foreground "PaleGreen"))))
                        '(org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
                        '(org-scheduled-previously ((t (:foreground "chocolate1"))))
                        '(org-upcoming-deadline ((t (:foreground "chocolate1"))))
                        '(org-agenda-restriction-lock ((t (:background "skyblue4"))))
                        '(org-time-grid ((t (:foreground "LightGoldenrod"))))
                        '(org-latex-and-export-specials ((t (:foreground "burlywood"))))
                        '(org-mode-line-clock-overrun ((t (:background "red"))))
                        '(sh-heredoc ((t (:foreground "yellow1" :weight bold))))
                        '(sh-quoted-exec ((t (:foreground "salmon"))))
                        '(epa-validity-high ((t (:foreground "PaleTurquoise" :weight bold))))
                        '(epa-validity-medium ((t (:foreground "PaleTurquoise" :slant italic))))
                        '(epa-validity-low ((t (:slant italic))))
                        '(epa-validity-disabled ((t (:inverse-video t :slant italic))))
                        '(epa-string ((t (:foreground "lightyellow"))))
                        '(epa-mark ((t (:foreground "orange" :weight bold))))
                        '(epa-field-name ((t (:foreground "PaleTurquoise" :weight bold))))
                        '(epa-field-body ((t (:foreground "turquoise" :slant italic)))))

(provide-theme 'tkzw)

;;; tkzw-theme.el ends here
